# testbench
CVAE_tb.v

# netlist generated by Design Compiler
../../SYN/DC/netlist/CVAE_top_syn.v

# Logic Gate models
-v /usr/cadtool/cad/synopsys/SAED32_EDK/lib/stdcell_hvt/verilog/saed32nm_hvt.v

../hdl/rams_sp_wf.v

+define+GATESIM
+access+r
